---
# Main tasks file for fubarhouse.nodejs

- include: setup.yml

- name: "Identify $USER"
  set_fact:
    fubarhouse_user: "{{ lookup('env','USER') }}"
  when: fubarhouse_user is not defined

- name: "Identify $HOME"
  set_fact:
    fubarhouse_user_dir: "{{ lookup('env','HOME') }}"
  when: fubarhouse_user_dir is not defined

- name: "Set default ivm installation directory"
  set_fact:
    ivm_install_dir: "{{ fubarhouse_user_dir }}/.ivm"
  when:
  - ivm_install_dir is not defined
  - install_ivm|bool == true

- name: "Set default nvm installation directory"
  set_fact:
    nvm_install_dir: "{{ fubarhouse_user_dir }}/.nvm"
  when:
  - nvm_install_dir is not defined
  - install_nvm|bool == true

- include: nvm.yml
  when: install_nvm

- include: ivm.yml
  when: install_ivm|bool == true

- include: nodejs.yml
  when: install_nodejs|bool == true

- include: iojs.yml
  when: install_iojs|bool == true

- include: npm.yml
  when: install_npm|bool == true